window.Modernizr=function(l,e,A){function v(b,d){for(var g in b){var f=b[g];if(!~(""+f).indexOf("-")&&y[f]!==A)return d=="pfx"?f:!0}return!1}function w(b,d,g){var f=b.charAt(0).toUpperCase()+b.slice(1),e=(b+" "+B.join(f+" ")+f).split(" ");if(typeof d==="string"||typeof d==="undefined")d=v(e,d);else{e=(b+" "+p.join(f+" ")+f).split(" ");a:{var b=e,h;for(h in b)if(f=d[b[h]],f!==A){d=g===!1?b[h]:typeof f==="function"?f.bind(g||d):f;break a}d=!1}}return d}var g={},z=e.documentElement,h=e.createElement("modernizr"),
y=h.style,D=" -webkit- -moz- -o- -ms- ".split(" "),B="Webkit Moz O ms".split(" "),p="webkit moz o ms".split(" "),h={},l=[],r=l.slice,m,x={}.hasOwnProperty,s;typeof x!=="undefined"&&typeof x.call!=="undefined"?s=function(b,d){return x.call(b,d)}:s=function(b,d){return d in b&&typeof b.constructor.prototype[d]==="undefined"};Function.prototype.bind||(Function.prototype.bind=function(b){var d=this;if(typeof d!="function")throw new TypeError;var g=r.call(arguments,1),f=function(){if(this instanceof f){var e=
function(){};e.prototype=d.prototype;var e=new e,h=d.apply(e,g.concat(r.call(arguments)));return Object(h)===h?h:e}return d.apply(b,g.concat(r.call(arguments)))};return f});h.cssgradients=function(){var b=("background-image:"+"-webkit- ".split(" ").join("gradient(linear,left top,right bottom,from(#9f9),to(white));background-image:")+D.join("linear-gradient(left top,#9f9, white);background-image:")).slice(0,-17);y.cssText=b;return!!~(""+y.backgroundImage).indexOf("gradient")};h.csstransforms=function(){return!!w("transform")};
for(var t in h)s(h,t)&&(m=t.toLowerCase(),g[m]=h[t](),l.push((g[m]?"":"no-")+m));g.addTest=function(b,d){if(typeof b=="object")for(var e in b)s(b,e)&&g.addTest(e,b[e]);else{b=b.toLowerCase();if(g[b]!==A)return g;d=typeof d=="function"?d():d;typeof!0!="undefined"&&(z.className+=" "+(d?"":"no-")+b);g[b]=d}return g};y.cssText="";return h=null,function(b,d){function e(){var a=C.elements;return typeof a=="string"?a.split(" "):a}function g(E){var c=I[E[a]];return c||(c={},u++,E[a]=u,I[u]=c),c}function h(a,
c,k){c||(c=d);if(q)return c.createElement(a);k||(k=g(c));var i;return k.cache[a]?i=k.cache[a].cloneNode():r.test(a)?i=(k.cache[a]=k.createElem(a)).cloneNode():i=k.createElem(a),i.canHaveChildren&&!p.test(a)?k.frag.appendChild(i):i}function l(a,c){c.cache||(c.cache={},c.createElem=a.createElement,c.createFrag=a.createDocumentFragment,c.frag=c.createFrag());a.createElement=function(k){return C.shivMethods?h(k,a,c):c.createElem(k)};a.createDocumentFragment=Function("h,f","return function(){var n=f.cloneNode(),c=n.createElement;h.shivMethods&&("+
e().join().replace(/\w+/g,function(a){return c.createElem(a),c.frag.createElement(a),'c("'+a+'")'})+");return n}")(C,c.frag)}function m(a){a||(a=d);var c=g(a);if(C.shivCSS&&!o&&!c.hasCSS){var k,i=a;k=i.createElement("p");i=i.getElementsByTagName("head")[0]||i.documentElement;k=(k.innerHTML="x<style>article,aside,figcaption,figure,footer,header,hgroup,nav,section{display:block}mark{background:#FF0;color:#000}</style>",i.insertBefore(k.lastChild,i.firstChild));c.hasCSS=!!k}return q||l(a,c),a}var n=
b.html5||{},p=/^<|^(?:button|map|select|textarea|object|iframe|option|optgroup)$/i,r=/^(?:a|b|code|div|fieldset|h1|h2|h3|h4|h5|h6|i|label|li|ol|p|q|span|strong|style|table|tbody|td|th|tr|ul)$/i,o,a="_html5shiv",u=0,I={},q;(function(){try{var a=d.createElement("a");a.innerHTML="<xyz></xyz>";o="hidden"in a;q=a.childNodes.length==1||function(){d.createElement("a");var a=d.createDocumentFragment();return typeof a.cloneNode=="undefined"||typeof a.createDocumentFragment=="undefined"||typeof a.createElement==
"undefined"}()}catch(c){o=!0,q=!0}})();var C={elements:n.elements||"abbr article aside audio bdi canvas data datalist details figcaption figure footer header hgroup mark meter nav output progress section summary time video",shivCSS:n.shivCSS!==!1,supportsUnknownElements:q,shivMethods:n.shivMethods!==!1,type:"default",shivDocument:m,createElement:h,createDocumentFragment:function(a,c){a||(a=d);if(q)return a.createDocumentFragment();for(var c=c||g(a),k=c.frag.cloneNode(),i=0,b=e(),u=b.length;i<u;i++)k.createElement(b[i]);
return k}};b.html5=C;m(d)}(this,e),g._version="2.6.2",g._prefixes=D,g._domPrefixes=p,g._cssomPrefixes=B,g.testProp=function(b){return v([b])},g.testAllProps=w,z.className=z.className.replace(/(^|\s)no-js(\s|$)/,"$1$2")+(" js "+l.join(" ")),g}(this,this.document);
(function(l,e,A){function v(a){return"[object Function]"==x.call(a)}function w(a){return"string"==typeof a}function g(){}function z(a){return!a||"loaded"==a||"complete"==a||"uninitialized"==a}function h(){var a=s.shift();t=1;a?a.t?r(function(){("c"==a.t?o.injectCss:o.injectJs)(a.s,0,a.a,a.x,a.e,1)},0):(a(),h()):t=0}function y(a,b,g,q,f,E,c){function k(c){if(!L&&z(i.readyState)&&(M.r=L=1,!t&&h(),i.onload=i.onreadystatechange=null,c)){"img"!=a&&r(function(){G.removeChild(i)},50);for(var k in n[b])n[b].hasOwnProperty(k)&&
n[b][k].onload()}}var c=c||o.errorTimeout,i=e.createElement(a),L=0,l=0,M={t:g,s:b,e:f,a:E,x:c};1===n[b]&&(l=1,n[b]=[]);"object"==a?i.data=b:(i.src=b,i.type=a);i.width=i.height="0";i.onerror=i.onload=i.onreadystatechange=function(){k.call(this,l)};s.splice(q,0,M);"img"!=a&&(l||2===n[b]?(G.insertBefore(i,d?null:m),r(k,c)):n[b].push(i))}function D(a,b,d,e,g){return t=0,b=b||"j",w(a)?y("c"==b?N:f,a,b,this.i++,d,e,g):(s.splice(this.i++,0,a),1==s.length&&h()),this}function B(){var a=o;return a.loader={load:D,
i:0},a}var p=e.documentElement,r=l.setTimeout,m=e.getElementsByTagName("script")[0],x={}.toString,s=[],t=0,b="MozAppearance"in p.style,d=b&&!!e.createRange().compareNode,G=d?p:m.parentNode,p=l.opera&&"[object Opera]"==x.call(l.opera),p=!!e.attachEvent&&!p,f=b?"object":p?"script":"img",N=p?"script":f,H=Array.isArray||function(a){return"[object Array]"==x.call(a)},F=[],n={},K={timeout:function(a,b){return b.length&&(a.timeout=b[0]),a}},J,o;o=function(a){function b(a){var a=a.split("!"),c=F.length,d=
a.pop(),e=a.length,d={url:d,origUrl:d,prefixes:a},g,j,h;for(j=0;j<e;j++)h=a[j].split("="),(g=K[h.shift()])&&(d=g(d,h));for(j=0;j<c;j++)d=F[j](d);return d}function d(a,c,e,g,h){var j=b(a),f=j.autoCallback;j.url.split(".").pop().split("?").shift();j.bypass||(c&&(c=v(c)?c:c[a]||c[g]||c[a.split("/").pop().split("?")[0]]),j.instead?j.instead(a,c,e,g,h):(n[j.url]?j.noexec=!0:n[j.url]=1,e.load(j.url,j.forceCSS||!j.forceJS&&"css"==j.url.split(".").pop().split("?").shift()?"c":A,j.noexec,j.attrs,j.timeout),
(v(c)||v(f))&&e.load(function(){B();c&&c(j.origUrl,h,g);f&&f(j.origUrl,h,g);n[j.url]=2})))}function e(a,c){function b(a,e){if(a)if(w(a))e||(j=function(){var a=[].slice.call(arguments);q.apply(this,a);l()}),d(a,j,c,0,h);else{if(Object(a)===a)for(m in u=function(){var c=0,b;for(b in a)a.hasOwnProperty(b)&&c++;return c}(),a)a.hasOwnProperty(m)&&(!e&&!--u&&(v(j)?j=function(){var a=[].slice.call(arguments);q.apply(this,a);l()}:j[m]=function(a){return function(){var c=[].slice.call(arguments);a&&a.apply(this,
c);l()}}(q[m])),d(a[m],j,c,m,h))}else!e&&l()}var h=!!a.test,f=a.load||a.both,j=a.callback||g,q=j,l=a.complete||g,u,m;b(h?a.yep:a.nope,!!f);f&&b(f)}var h,f,c=this.yepnope.loader;if(w(a))d(a,0,c,0);else if(H(a))for(h=0;h<a.length;h++)f=a[h],w(f)?d(f,0,c,0):H(f)?o(f):Object(f)===f&&e(f,c);else Object(a)===a&&e(a,c)};o.addPrefix=function(a,b){K[a]=b};o.addFilter=function(a){F.push(a)};o.errorTimeout=1E4;null==e.readyState&&e.addEventListener&&(e.readyState="loading",e.addEventListener("DOMContentLoaded",
J=function(){e.removeEventListener("DOMContentLoaded",J,0);e.readyState="complete"},0));l.yepnope=B();l.yepnope.executeStack=h;l.yepnope.injectJs=function(a,b,d,f,l,n){var c=e.createElement("script"),k,i,f=f||o.errorTimeout;c.src=a;for(i in d)c.setAttribute(i,d[i]);b=n?h:b||g;c.onreadystatechange=c.onload=function(){!k&&z(c.readyState)&&(k=1,b(),c.onload=c.onreadystatechange=null)};r(function(){k||(k=1,b(1))},f);l?c.onload():m.parentNode.insertBefore(c,m)};l.yepnope.injectCss=function(a,b,d,f,l,n){var f=
e.createElement("link"),c,b=n?h:b||g;f.href=a;f.rel="stylesheet";f.type="text/css";for(c in d)f.setAttribute(c,d[c]);l||(m.parentNode.insertBefore(f,m),r(b,0))}})(this,document);Modernizr.load=function(){yepnope.apply(window,[].slice.call(arguments,0))};
